spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mysql://localhost:3306/eco100?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: eco100
    password: mapo

  jpa:
    hibernate:
      ddl-auto: update
      #generate-ddl이 true이면 서버를 켜면 ddl문이 실행된다
    generate-ddl: true

    properties:
      format_sql: true
      hibernate:
        show-sql: false

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        
# logging:
#   level:
#     org.hibernate.SQL: trace
#     org.hibernate.type: trace