spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:eco100DB
    driver-class-name: org.h2.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
      #generate-ddl이 true이면 서버를 켜면 ddl문이 실행된다
    generate-ddl: true

    properties:
      format_sql: true
      hibernate:
        show-sql: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
        
logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace